server {
    listen 80;

    # Lo que empiece por /api se va a FastAPI
    location /api/ {
        proxy_pass http://ai-engine:8000/; # El slash final es importante
        proxy_set_header Host $host;
    }

    # El resto a Django
    location / {
        proxy_pass http://backend-django:8080;
        proxy_set_header Host $host;
    }
}