# Generated by Django 5.2.13 on 2026-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAuditado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='contratos/')),
                ('tipo', models.CharField(choices=[('alquiler', 'Alquiler'), ('nda', 'NDA')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('riesgo', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
